{% set version = "0.16.1" %}
{% set htslib_version = "1.18" %}

package:
  name: bambi-pkg
  version: "{{ version }}"

about:
  home: https://github.com/wtsi-npg/bambi
  license: AGPL
  summary: "A set of programs to manipulate SAM/BAM/CRAM files, using HTSLIB."

build:
  number: 1

source:
  git_url: https://github.com/wtsi-npg/bambi.git
  git_rev: {{ version }}

requirements:
  build:
    - {{ compiler("c") }}
    - autoconf
    - automake
    - make
    - perl
    - pkg-config
  host:
    - libgd-dev
    - libhts-dev =={{ htslib_version }}
    - libxml2-dev
    - libz-dev
  run:
    - libgd
    - libhts =={{ htslib_version }}
    - libxml2
    - libz

outputs:
  - name: bambi
    requirements:
      build:
        - {{ compiler("c") }}
        - autoconf
        - automake
        - make
        - perl
        - pkg-config
      host:
        - libgd-dev
        - libhts-dev =={{ htslib_version }}
        - libxml2-dev
        - libz-dev
      run:
        - libgd
        - libhts =={{ htslib_version }}
        - libxml2
        - libz
    files:
      - bin/bambi
      - bin/check_bcl

test:
  commands:
    - bambi --version
